/*CREATE TABLE province(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
active BOOLEAN DEFAULT true
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
*/
CREATE TABLE district(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
-- province_id BIGINT(20) NOT NULL, 
active BOOLEAN DEFAULT true
-- FOREIGN KEY(province_id) REFERENCES province(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE operational_site(
id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
target BIGINT NOT NULL DEFAULT '0',
district_id BIGINT NOT NULL,
active BOOLEAN DEFAULT true,
CONSTRAINT fk_district_opsite
FOREIGN KEY(district_id) REFERENCES district(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE locality(
id BIGINT AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
operational_site_id BIGINT NOT NULL,
active BOOLEAN DEFAULT true,
PRIMARY KEY(id),
CONSTRAINT fk_locality_opSite
 FOREIGN KEY(operational_site_id) REFERENCES operational_site(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE village(
id BIGINT(20) AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
locality_id BIGINT,
revisits BIGINT NOT NULL DEFAULT '0',
active BOOLEAN DEFAULT true,
PRIMARY KEY(id),
CONSTRAINT fk_locality_village
  FOREIGN KEY(locality_id) REFERENCES locality(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;